version: '2.1'

services:
  localstack_test:
    image: localstack/localstack:0.7.0
    ports:
      - "4476:4476"
    environment:
      - SERVICES=sqs:4476
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
